spring.application.name=planmate

//DB
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=386902
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
//MyBatis
mybatis.mapper-locations=classpath:mybatis/*.xml
mybatis.type-aliases-package=com.Seproject.planmate.dto
logging.level.org.apache.ibatis=DEBUG

# 데이터베이스 연결 및 실행에 대한 로그 설정 (필요 시)
logging.level.java.sql=DEBUG
logging.level.jdbc.sqlonly=DEBUG
logging.level.jdbc.resultsettable=TRACE
logging.level.jdbc.connection=DEBUG
