DROP TABLE STUDENT CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;

CREATE TABLE DEPARTMENT (
    DEPARTMENT_CODE CHAR(6) PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(80) NOT NULL
);

CREATE TABLE STUDENT (
    STUDENT_CODE CHAR(6) PRIMARY KEY,
    STUDENT_NAME VARCHAR2(80) NOT NULL,
    DEPARTMENT_CODE CHAR(6) REFERENCES DEPARTMENT(DEPARTMENT_CODE),
    ID VARCHAR2(128) NOT NULL,
    PASSWORD VARCHAR2(128) NOT NULL
);